# Generated by Django 3.2.20 on 2023-08-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameM', models.CharField(max_length=300)),
                ('emailM', models.CharField(max_length=200)),
                ('addressM', models.CharField(max_length=300)),
                ('phoneM', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'employee_tb',
            },
        ),
    ]
