# Generated by Django 3.2.20 on 2023-08-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='actionM',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
