# Generated by Django 3.2.20 on 2023-08-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_employee_actionm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='actionM',
        ),
    ]
